version: 2.18.1
services:
    bigdata:
        container_name: bigdata_server
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            JAVA_HOME: /usr/lib/jvm/java-11-openjdk-arm64
            DATABASE_URL: mongodb://mongodb:27017
        ports:
            - 3004:3004
        depends_on:
            - mongodb
        volumes:
            - ./app:/code/app
    mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - 27017:27017
        volumes:
            - ./data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
